export const books = [
  {
    id: 'bk-1',
    title: 'Python pour les entrepreneurs digitaux',
    slug: 'python-pour-entrepreneurs-digitaux',
    price: 8500,
    category: 'Programmation',
    author: 'A. Diarra',
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800&q=80',
    description: 'Guide pratique pour comprendre Python et automatiser vos tâches métier.',
  },
  {
    id: 'bk-2',
    title: 'Cybersécurité et protection des données',
    slug: 'cybersecurite-protection-donnees',
    price: 9500,
    category: 'Sécurité',
    author: 'M. Nikiema',
    image: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=800&q=80',
    description: 'Apprenez les bases de la sécurité numérique et la gestion des risques.',
  },
  {
    id: 'bk-3',
    title: 'IA appliquée au business local',
    slug: 'ia-appliquee-au-business-local',
    price: 11000,
    category: 'IA',
    author: 'K. Sawadogo',
    image: 'https://images.unsplash.com/photo-1522542550221-31fd19575a2d?auto=format&fit=crop&w=800&q=80',
    description: 'Utilisez l’intelligence artificielle pour améliorer vos offres et services.',
  },
  {
    id: 'bk-4',
    title: 'Marketing digital au Burkina Faso',
    slug: 'marketing-digital-burkina-faso',
    price: 7000,
    category: 'Marketing',
    author: 'S. Ouedraogo',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=800&q=80',
    description: 'Des stratégies concrètes pour vendre en ligne avec efficacité.',
  },
];
